### ISSUE TITLE
Compatibility with replicates?

### ISSUE THREAD

**Issue by cohenp05** [HectorRDB/condiments#13]
Hello,

Thanks for a great package! It's an exciting piece of work. I have a dataset with 5 conditions (a mock and two treatments, and each treatment has two timepoints). For each condition there are 2-3 replicates. The 12 samples were multiplexed and processed in three batches in an attempt to minimize batch effect.  After TI, there seem to be 3 lineages within the dataset.

My question is: how best should I analyze those replicates with condiments. Can the tests implemented in condiments incorporate replicate samples into their testing? Will having replicate samples across multiple batches be compatible with the assumptions made in the various statistical tests implemented in condiments? 

Thank you for your help!

**Comment by HectorRDB** [comment]
Hi @cohenp05 
Thanks for trying out condiments, I'm glad you like it. Sorry for taking some time to respond, I was on a break. 

some dimensionality reduction methods can take batches into account. As those serves as input for condiments, this is one way to take advantage of your replicates. Since replicates in scRNA-Seq tend to be limited (for example 2-3 in your case) and as such, are mostly used to remove sequencing batch effect, we do not really consider it in condiments.

For now, steps 1 and 2 of condiments do not take samples into account. However, your experiment design is sound and should minimize batch effect between conditions. 
For step 3 (differential expression), you can add batch (or even sample) as a covariate using the U parameter. In that case, each gene will have a distinct constant coefficient for each batch. 

I hope that helps,
Best

**Comment by cohenp05** [comment]
Thanks, @HectorRDB ! That sounds like a great solution
