### ISSUE TITLE
topology test question

### ISSUE THREAD

**Issue by lb15** [HectorRDB/condiments#4]
Hi, thanks for a great package! I am using this package along with slingshot and tradeSeq to look at genes changing over pseudotime in 3 different conditions. We have some biological expectations, where 2 of our conditions we expect a "blocking" of differentiation. I have generated a slingshot object with 2 lineages and then performed the topology test to determine if i can fit a single trajectory or need separate trajectories. The topology test rejected the null, so I went on to fit three separate trajectories. I find that the trajectories appear very similar - as I would also expect from the UMAP representation, where we have reduced number of cells in one trajectory (the long U-shaped tail), but the overall structure is similar. The MST looks slightly different, but it may because I simplified the clusters for slingshot to just 4 clusters in order to get only 2, smooth lineages.
<img width="432" alt="Screen Shot 2021-07-21 at 12 03 30 PM" src="https://user-images.githubusercontent.com/40410297/126545211-c4301813-e030-4577-a95c-758bcecbae15.png">
<img width="434" alt="Screen Shot 2021-07-21 at 12 03 20 PM" src="https://user-images.githubusercontent.com/40410297/126545226-65e943b4-afee-4482-90a3-b5a5b3fb2a80.png">

I saw in the paper that it was important to reconcile separate trajectories in order to appropriately use progressionTest and downstream conditionTests. My question is, do these 3 separate trajectories appear similar enough to utilize the downstream tests or do I need to worry about the results of the topology test and MSTs? 

Thanks!!

**Comment by HectorRDB** [comment]
Hi @lb15 
Thanks for the feedbacks, they are greatly appreciated.
We are still tinkering with the appropriate rejection threshold for the topologyTest. Because we lack a large variety of datasets, it's been hard deciding on a proper framework that would work with everyone.

In your case, I would imagine that the topologyTest rejects the null because the shortened orange lineage makes it very unstable to fit.  Could you let me know the output of the test (test statistics and p-value) ?
Therefore, in your case, I would definitely proceed with a common trajectory and conduct the analysis from step 2 (progressionTest and differentiationTest).
Let me know if you have any other troubles,
Best

**Comment by HectorRDB** [comment]
Closing after a month of inactivity. Feel free to re-open if the issue persists
